### ISSUE TITLE
Not able to build and run this application

### ISSUE THREAD

**Issue by BillyYiuCimda** [CrazyChaoz/Minimal_Working_UWB_App#2]
I am not able to build and run this application in Windows 10 because of the following message. Do you have any idea how to solve this problem?
Execution failed for task ':app:processDebugResources'.
> Could not isolate parameters com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@61e1fa52 of artifact transform AarResourcesCompilerTransform
   > Could not isolate value com.android.build.gradle.internal.dependency.AarResourcesCompilerTransform$Parameters_Decorated@61e1fa52 of type AarResourcesCompilerTransform.Parameters
      > Dependency verification failed for configuration ':app:detachedConfiguration2'

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:processDebugResources'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)

**Comment by CrazyChaoz** [comment]
That issue appears when you try to update some dependencies, that specific one is with ```androidx.appcompat:appcompat``` I believe.

I'll try to find out more ASAP.

Edit: In the end it looks like a dependency verification issue. If you're not using nix and you don't want to do dependency verification you just have to delete the **_gradle/verification-metadata.xml_** file.

**Comment by BillyYiuCimda** [comment]
Thanks, it solved my compilation problem.
